[package]
name = "shu-mcp"
version = "0.1.0"
edition = "2024"
description = "SHU MCP Server implementation"
license = "MIT"
repository = "https://github.com/preca-hoshino/shu-mcp"
keywords = ["mcp", "server"]
categories = ["development-tools"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
reqwest = { version = "0.12", features = ["json"] }
urlencoding = "2.1.3"

tokio = { version = "1.51.1", features = ["full"] }
rust-mcp-sdk = "0.9.0"
async-trait = "0.1.89"
glob = "0.3.2"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
missing_debug_implementations = "deny"
unused = { level = "deny", priority = -1 }
rust_2024_compatibility = { level = "deny", priority = -1 }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
missing_docs_in_private_items = "deny"
multiple_crate_versions = "allow"
